appName: elastalert-server
port: 3030
wsport: 3333
elastalertPath: /opt/elastalert
verbose: false
es_debug: false
debug: false
rulesPath:
  relative: true
  path: /rules
templatesPath:
  relative: true
  path: /rule_templates
es_host:
es_port:
writeback_index: elastalert_status
