apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "elastalert.fullname" . }}-config
  labels:
    app: {{ template "elastalert.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  elastalert_config: |-
    ---
    rules_folder: /opt/elastalert/rules
    scan_subdirectories: false
    run_every:
      minutes: {{ .Values.runIntervalMins }}
{{- if .Values.realertIntervalMins }}
    realert:
      minutes: {{ .Values.realertIntervalMins }}
{{- end }}
    buffer_time:
      minutes: {{ .Values.bufferTimeMins }}
    es_host: {{ .Values.elasticsearch.host }}
    es_port: {{ .Values.elasticsearch.port }}
{{- if .Values.elasticsearch.username }}
    es_username: {{ .Values.elasticsearch.username }}
{{- end }}
{{- if .Values.elasticsearch.password }}
    es_password: {{ .Values.elasticsearch.password }}
{{- end }}
    writeback_index: {{ .Values.writebackIndex }}
    use_ssl: {{ .Values.elasticsearch.useSsl }}
    verify_certs: {{ .Values.elasticsearch.verifyCerts }}
{{- if .Values.elasticsearch.clientCert }}
    client_cert: {{ .Values.elasticsearch.clientCert }}
{{- end }}
{{- if .Values.elasticsearch.clientKey }}
    client_key: {{ .Values.elasticsearch.clientKey }}
{{- end }}
{{- if .Values.elasticsearch.caCerts }}
    ca_certs: {{ .Values.elasticsearch.caCerts }}
{{- end }}
    alert_time_limit:
      minutes: {{ .Values.alertRetryLimitMins }}
{{- if .Values.extraConfigOptions }}
{{ toYaml .Values.extraConfigOptions | indent 4 }}
{{- end }}

  elastalert_test: |-
    -----
    rules_folder: /opt/elastalert/rules
    run_every:
      minutes: {{ .Values.runIntervalMins }}
{{- if .Values.elasticsearch.host }}
    es_host: {{.Values.elasticsearch.host }}
{{- end }}
{{- if .Values.elasticsearch.port }}
    es_port: {{.Values.elasticsearch.port }}
{{- end }}
    buffer_time:
      minutes: {{ .Values.bufferTimeMins }}
{{- if .Values.writebackIndex }}
    writeback_index: {{.Values.writebackIndex }}
{{- end }}
    alert_time_limit:
      minutes: {{ .Values.alertRetryLimitMins }}

  json_config: |-
    {
      "appName": "{{ .Values.serverConfig.appName }}",
      "port": {{ .Values.serverConfig.port }},
      "wsport": {{ .Values.serverConfig.wsport }},
      "elastalertPath": "{{ .Values.serverConfig.elastalertPath }}",
      "verbose": {{ .Values.serverConfig.verbose }},
      "es_debug": {{ .Values.serverConfig.es_debug }},
      "debug": {{ .Values.serverConfig.debug }},
      "rulesPath":{
        "relative": true,
        "path": "{{ .Values.serverConfig.rulesPath.path }}"
      },
      "templatesPath":{
        "relative": true,
        "path": "{{ .Values.serverConfig.templatesPath.path }}"
      },
      "dataPath": {
        "relative": true,
        "path": "{{ .Values.serverConfig.dataPath.path }}"
      },
      "es_host": "{{ .Values.elasticsearch.host }}",
      "es_port": {{ .Values.elasticsearch.port }},
      "writeback_index": "{{ .Values.writebackIndex }}"
    }
