{{ if .Values.elasticsearch.host }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "elastalert.fullname" . }}
  labels:
    app: {{ template "elastalert.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
        checksum/rules: {{ include (print $.Template.BasePath "/rules.yaml") . | sha256sum }}
      labels:
        name: {{ template "elastalert.fullname" . }}-elastalert
        app: {{ template "elastalert.name" . }}
        release: {{ .Release.Name }}
    spec:
{{- if .Values.securityContext }}
      securityContext:
{{toYaml .Values.securityContext | indent 8 }}
{{- end }}
{{- if .Values.ServiceAccount  }}
      serviceAccount: {{ .Values.ServiceAccount }}
{{- end }}
{{- if .Values.ServiceAccountName  }}
      serviceAccountName: {{ .Values.ServiceAccountName  }}
{{- end }}
      containers:
      - name: elastalert
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- if .Values.lifecycle.poststart }}
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh","-c","{{ .Values.lifecycle.poststart }}"]
{{- end }}
{{- if .Values.image.ports }}
        ports:
{{toYaml .Values.image.ports | indent 12}}
{{- end }}
{{- if .Values.image.net }}
        net: {{ .Values.image.net }}
{{- end }}
{{- if .Values.command }}
        command:
{{ toYaml .Values.command | indent 10 }}
{{- end }}
{{- if .Values.args }}
        args:
{{ toYaml .Values.args | indent 10 }}
{{- end }}
        volumeMounts:
          - name: config
            mountPath: '/opt/elastalert'
            readOnly: false
          - name: rules
            mountPath: '/opt/elastalert/rules'
            readOnly: false
          - name: configjs
            mountPath: '/opt/elastalert-server/config'
          - name: templaterules
            mountPath: '/opt/elastalert/rule_templates'
          - name: server
            mountPath: '/opt/elastalert/server_data'
{{- if .Values.elasticsearch.certsVolumeMounts }}
{{ toYaml .Values.elasticsearch.certsVolumeMounts | indent 10 }}
{{- end }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
      restartPolicy: Always
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
{{- end }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
      volumes:
        - name: templaterules
          configMap:
            defaultMode: 460
            name: {{ template "elastalert.fullname" . }}-rules
            items:
 {{- range $key, $value := .Values.rulesshared }}         
             - key: {{ $key }}
               path: {{ $key }}.yaml 
 {{- end }}            
{{ if and .Values.environment.type (eq .Values.environment.type "datafoundrydev") }}            
 {{- range $key, $value := .Values.rulesdatafoundrydev }}         
             - key: {{ $key }}
               path: {{ $key }}.yaml 
 {{- end }}
{{- end }}
{{ if and .Values.environment.type (eq .Values.environment.type "datafoundry") }} 
 {{- range $key, $value := .Values.rulesdatafoundry }}         
             - key: {{ $key }}
               path: {{ $key }}.yaml 
 {{- end }}
{{- end }}
        - name: config
          configMap:
            defaultMode: 420
            name: {{ template "elastalert.fullname" . }}-config
            items:
            - key: elastalert_config
              path: config.yaml
            - key: elastalert_test
              path: config-test.yaml
        - name: configjs
          configMap:
            defaultMode: 420
            name: {{ template "elastalert.fullname" . }}-config
            items:
            - key: json_config
              path: config.json
        - name: rules
        - name: server
{{- if .Values.elasticsearch.certsVolumes }}
{{ toYaml .Values.elasticsearch.certsVolumes | indent 8 }}
{{- end }}
{{- end }}

