apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "elastalert.fullname" . }}-rules
  labels:
    app: {{ template "elastalert.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    
    
data:
{{- range $key, $value := .Values.rulesshared }}
{{ $key | indent 2}}: |-
{{ $value | indent 4}}
{{- end }}
{{ if and .Values.environment.type (eq .Values.environment.type "datafoundrydev") }}
{{- range $key, $value := .Values.rulesdatafoundrydev }}
{{ $key | indent 2}}: |-
{{ $value | indent 4}}
{{- end }}
{{- end }}
{{ if and .Values.environment.type (eq .Values.environment.type "datafoundry") }} 
{{- range $key, $value := .Values.rulesdatafoundry }}
{{ $key | indent 2}}: |-
{{ $value | indent 4}}
{{- end }}
{{- end }}